describe("Test Mid-level API", () => {
  it("should run mid-level api example", () => {
    cy.visit("/mid_level/command.html");
    cy.get("#YAGNA_APPKEY").clear().type(Cypress.env("YAGNA_APPKEY"));
    cy.get("#YAGNA_API_BASEPATH").clear().type(Cypress.env("YAGNA_API_BASEPATH"));
    cy.get("#SUBNET_TAG").clear().type(Cypress.env("YAGNA_SUBNET"));
    cy.get("#createPackage").click().debug();
    cy.wait(500);
    cy.get("#logs").should("include.text", "Package created");
    cy.get("#createAllocation").click();
    cy.wait(2000);
    cy.get("#logs").should("match", /Allocation .* has been created/);
    cy.get("#createDemand").click();
    cy.wait(2000);
    cy.get("#logs").should("include.text", "Demand published on teh market");
    cy.wait(3000);
    cy.get("#logs").should("include.text", "New proposal has been received");
    cy.get("#respondProposal").click();
    cy.wait(3000);
    cy.get("#logs").should("include.text", "New offer has been received");
    cy.get("#createAgreement").click();
    cy.wait(1000);
    cy.get("#logs").should("match", /Agreement .* created/);
    cy.get("#confirmAgreement").click();
    cy.wait(1000);
    cy.get("#logs").should("match", /Agreement .* approved/);
    cy.get("#createActivity").click();
    cy.wait(2000);
    cy.get("#logs").should("match", /Activity .* approved/);
    cy.get("#COMMAND").clear().type("echo 'Hello Golem'");
    cy.get("#execute").click();
    cy.wait(2000);
    cy.get("#logs").should("include.text", "Script sent");
    cy.get("#results").should("include.text", "Hello Golem");
    cy.get("#end").click();
    cy.wait(3000);
    cy.get("#logs").should("match", /Activity .* destroyed/);
    cy.get("#logs").should("match", /Agreement .* terminated/);
    cy.get("#logs").should("match", /Allocation .* has been released/);
    cy.get("#logs").should("match", /Demand .* unsubscribed/);
  });
});
