<template>
  <el-card class="card-box" v-loading="loading">
    <template #header>
      <div class="card-header">
        <span>Demand</span>
        <el-button type="success" @click="createDemand" v-if="!theDemand && isReady">Create Demand</el-button>
      </div>
    </template>
    <p v-if="!isReady">To create demand create allocation and package first</p>
    <p v-else-if="!theDemand">To start receiving proposals create a demand first</p>
    <p v-else>Table will be here</p>
    <el-table :data="proposalsTable" border table-layout="auto" size="small">
      <el-table-column type="expand">
        <template #default="props">
          <div class="expandable">
            <dl>
              <dt>ID:</dt>
              <dd>{{ props.row.id }}</dd>
              <dt>Issuer ID:</dt>
              <dd>{{ props.row.issuerId }}</dd>
              <dt>Public Net:</dt>
              <dd>{{ props.row.public_net }}</dd>
              <dt>CPU Capabilities:</dt>
              <dd>{{ props.row.cpu_capabilities.join(", ") }}</dd>
              <dt>VM:</dt>
              <dd>{{ props.row.runtime_name }}</dd>
            </dl>
          </div>
        </template>
      </el-table-column>
      <el-table-column label="Platform" prop="cpu_brand" sortable />
      <el-table-column prop="provider_name" label="Provider" sortable />
      <el-table-column prop="state" label="State" sortable />
      <el-table-column prop="cpu_cores" label="Cores" sortable class-name="text-right" />
      <el-table-column prop="cpu_threads" label="Threads" sortable class-name="text-right" />
      <el-table-column
        prop="mem"
        label="Memory"
        sortable
        :formatter="(v) => `${new Number(v.mem).toFixed(2)} Gib`"
        class-name="text-right"
      />
      <el-table-column
        prop="storage"
        label="Storage"
        sortable
        :formatter="(v) => `${new Number(v.storage).toFixed(2)} Gib`"
        class-name="text-right"
      />
      <el-table-column label="Actions" class-name="actions">
        <template #default="scope">
          <el-button type="success" size="small" @click="createAgreement(scope.row)" v-if="scope.row.state === 'Draft'"
            >Create Agreement</el-button
          >
          <el-button type="info" size="small" @click="respondProposal(scope.row)" v-else>Respond</el-button>
        </template>
      </el-table-column>
    </el-table>
  </el-card>
</template>
<script setup>
import { Demand, DemandEventType } from "../../../../../dist/yajsapi.min.js";

const props = defineProps({
  yaTask: Object,
  yaOptions: Object,
});

const loading = ref(false);
const theDemand = ref();
const proposals = ref([]);
const isReady = computed(() => props.yaTask.package && props.yaTask.allocation);

const proposalsTable = computed(() =>
  proposals.value.map((p) => {
    return {
      id: p.id,
      transfer_protocol: p.properties["golem.activity.caps.transfer.protocol"],
      cpu_brand: p.properties["golem.inf.cpu.brand"],
      cpu_capabilities: p.properties["golem.inf.cpu.capabilities"],
      cpu_cores: p.properties["golem.inf.cpu.cores"],
      cpu_threads: p.properties["golem.inf.cpu.threads"],
      mem: p.properties["golem.inf.mem.gib"],
      storage: p.properties["golem.inf.storage.gib"],
      provider_name: p.properties["golem.node.id.name"],
      public_net: p.properties["golem.node.net.is-public"],
      runtime_capabilities: p.properties["golem.runtime.capabilities"],
      runtime_name: p.properties["golem.runtime.name"],
      issuerId: p.issuerId,
      state: p.state,
    };
  })
);

const createAgreement = async ({ id }) => {};
const respondProposal = async ({ id }) => {
  const index = proposals.value.findIndex((p) => p.id === id);

  if (index >= 0) {
    const proposal = proposals.value[index];
    const proposalId = await proposal.respond(props.yaTask.allocation.platform).catch(console.error);
    proposals.value[index].counterProposalId = proposalId;
  }
};

let count = 0;

const createDemand = async () => {
  loading.value = true;

  const demand = await Demand.create(props.yaTask.package, [props.yaTask.allocation], props.yaOptions).catch(
    console.error
  );
  loading.value = false;
  theDemand.value = demand;
  demand.addEventListener(DemandEventType, async (event) => {
    console.log(event.proposal);
    if (event.proposal.state === "Draft") {
      const index = proposals.value.findIndex((p) => {
        return p.counterProposalId === event.proposal.prevProposalId;
      });
      if (index >= 0) {
        proposals.value[index] = event.proposal;
      }
    } else {
      proposals.value.push(event.proposal);
    }
  });
};

// proposals.value.push({
//   subscriptionId: "75fb0c0c043e44eeacb4a019a387832a-ee70e77ec616a104251016504c9997be654f81a966ac6bf7106a3d6e0a373617",
//   api: {
//     basePath: "http://127.0.0.1:7465/market-api/v1",
//     configuration: {
//       apiKey: "30c59fef7d8c4639b62d576bfb624e1a",
//       accessToken: "30c59fef7d8c4639b62d576bfb624e1a",
//       basePath: "http://127.0.0.1:7465/market-api/v1",
//     },
//   },
//   demandRequest: {
//     constraints:
//       "(&(golem.inf.mem.gib>=1)\n\t(golem.inf.storage.gib>=1)\n\t(golem.runtime.name=vm)\n\t(golem.inf.cpu.threads>=1)\n\t(golem.com.payment.platform.erc20-rinkeby-tglm.address=*)\n\t(golem.com.pricing.model=linear)\n\t(golem.node.debug.subnet=public))",
//     properties: {
//       "golem.srv.comp.task_package":
//         "hash:sha3:9a3b5d67b0b27746283cb5f287c13eab1beaa12d92a9f536b747c7ae:http://girepo.dev.golem.network:8000/local-image-c76719083b.gvmi\n",
//       "golem.srv.comp.vm.package_format": "gvmkit-squash",
//       "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xdc9b51c37a6f45a5fdc9af6ea04e00f7c64a2b6f",
//       "golem.srv.caps.multi-activity": true,
//       "golem.srv.comp.expiration": 1677251265172,
//       "golem.node.debug.subnet": "public",
//     },
//   },
//   eventTarget: {},
//   id: "R-b06fe110137d583bc5273f91d2663cee94e4be412a34d3428f7275fea646691f",
//   issuerId: "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//   properties: {
//     "golem.activity.caps.transfer.protocol": ["http", "gftp", "https"],
//     "golem.com.payment.debit-notes.accept-timeout?": 240,
//     "golem.com.payment.platform.erc20-goerli-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-mumbai-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.pricing.model": "linear",
//     "golem.com.pricing.model.linear.coeffs": [0.0001, 0.00005, 0],
//     "golem.com.scheme": "payu",
//     "golem.com.scheme.payu.debit-note.interval-sec?": 120,
//     "golem.com.scheme.payu.payment-timeout-sec?": 120,
//     "golem.com.usage.vector": ["golem.usage.cpu_sec", "golem.usage.duration_sec"],
//     "golem.inf.cpu.architecture": "x86_64",
//     "golem.inf.cpu.brand": "Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz",
//     "golem.inf.cpu.capabilities": [
//       "sse3",
//       "pclmulqdq",
//       "dtes64",
//       "monitor",
//       "dscpl",
//       "vmx",
//       "smx",
//       "eist",
//       "tm2",
//       "ssse3",
//       "fma",
//       "cmpxchg16b",
//       "pdcm",
//       "pcid",
//       "sse41",
//       "sse42",
//       "x2apic",
//       "movbe",
//       "popcnt",
//       "tsc_deadline",
//       "aesni",
//       "xsave",
//       "osxsave",
//       "avx",
//       "f16c",
//       "rdrand",
//       "fpu",
//       "vme",
//       "de",
//       "pse",
//       "tsc",
//       "msr",
//       "pae",
//       "mce",
//       "cx8",
//       "apic",
//       "sep",
//       "mtrr",
//       "pge",
//       "mca",
//       "cmov",
//       "pat",
//       "pse36",
//       "clfsh",
//       "ds",
//       "acpi",
//       "mmx",
//       "fxsr",
//       "sse",
//       "sse2",
//       "ss",
//       "htt",
//       "tm",
//       "pbe",
//       "fsgsbase",
//       "adjust_msr",
//       "bmi1",
//       "hle",
//       "avx2",
//       "smep",
//       "bmi2",
//       "rep_movsb_stosb",
//       "invpcid",
//       "rtm",
//       "deprecate_fpu_cs_ds",
//       "mpx",
//       "rdseed",
//       "adx",
//       "smap",
//       "clflushopt",
//       "processor_trace",
//       "sgx",
//     ],
//     "golem.inf.cpu.cores": 4,
//     "golem.inf.cpu.model": "Stepping 9 Family 6 Model 302",
//     "golem.inf.cpu.threads": 2,
//     "golem.inf.cpu.vendor": "GenuineIntel",
//     "golem.inf.mem.gib": 8,
//     "golem.inf.storage.gib": 100,
//     "golem.node.debug.subnet": "public",
//     "golem.node.id.name": "sycamore.h",
//     "golem.node.net.is-public": false,
//     "golem.runtime.capabilities": ["inet", "vpn", "manifest-support", "start-entrypoint"],
//     "golem.runtime.name": "vm",
//     "golem.runtime.version": "0.3.0",
//     "golem.srv.caps.multi-activity": true,
//     "golem.srv.caps.payload-manifest": true,
//   },
//   constraints: "(&\n  (golem.srv.comp.expiration>1676011020268)\n  (golem.node.debug.subnet=public)\n)",
//   timestamp: "2023-02-24T14:52:45.266946Z",
//   state: "Initial",
//   _score: null,
// });
// proposals.value.push({
//   subscriptionId: "9b0514f70e5a4e78ac833d124b313338-a495520edf9f6a84e98dba0d386cf7bdd824565b97ee2c4cb44711b5cace0322",
//   api: {
//     basePath: "http://127.0.0.1:7465/market-api/v1",
//     configuration: {
//       apiKey: "30c59fef7d8c4639b62d576bfb624e1a",
//       accessToken: "30c59fef7d8c4639b62d576bfb624e1a",
//       basePath: "http://127.0.0.1:7465/market-api/v1",
//     },
//   },
//   demandRequest: {
//     constraints:
//       "(&(golem.inf.mem.gib>=1)\n\t(golem.inf.storage.gib>=1)\n\t(golem.runtime.name=vm)\n\t(golem.inf.cpu.threads>=1)\n\t(golem.com.payment.platform.erc20-rinkeby-tglm.address=*)\n\t(golem.com.pricing.model=linear)\n\t(golem.node.debug.subnet=public))",
//     properties: {
//       "golem.srv.comp.task_package":
//         "hash:sha3:9a3b5d67b0b27746283cb5f287c13eab1beaa12d92a9f536b747c7ae:http://girepo.dev.golem.network:8000/local-image-c76719083b.gvmi\n",
//       "golem.srv.comp.vm.package_format": "gvmkit-squash",
//       "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xdc9b51c37a6f45a5fdc9af6ea04e00f7c64a2b6f",
//       "golem.srv.caps.multi-activity": true,
//       "golem.srv.comp.expiration": 1677252453387,
//       "golem.node.debug.subnet": "public",
//     },
//   },
//   eventTarget: {},
//   id: "R-f6ccf0bf7a30fb019af28670298d81bdf20d2e3db57fe0a7a71fd2a15a48efec",
//   issuerId: "0x6b3b050959aacc3666932852ee34eb290ce15111",
//   properties: {
//     "golem.activity.caps.transfer.protocol": ["https", "gftp", "http"],
//     "golem.com.payment.debit-notes.accept-timeout?": 240,
//     "golem.com.payment.platform.erc20-goerli-tglm.address": "0x9185748b999faaf4188717d3e0389493f18316d6",
//     "golem.com.payment.platform.erc20-mumbai-tglm.address": "0x9185748b999faaf4188717d3e0389493f18316d6",
//     "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0x9185748b999faaf4188717d3e0389493f18316d6",
//     "golem.com.pricing.model": "linear",
//     "golem.com.pricing.model.linear.coeffs": [0.000006944444444444445, 0.000001388888888888889, 0],
//     "golem.com.scheme": "payu",
//     "golem.com.scheme.payu.debit-note.interval-sec?": 120,
//     "golem.com.scheme.payu.payment-timeout-sec?": 120,
//     "golem.com.usage.vector": ["golem.usage.cpu_sec", "golem.usage.duration_sec"],
//     "golem.inf.cpu.architecture": "x86_64",
//     "golem.inf.cpu.brand": "AMD Ryzen 7 5700G with Radeon Graphics",
//     "golem.inf.cpu.capabilities": [
//       "sse3",
//       "pclmulqdq",
//       "monitor",
//       "ssse3",
//       "fma",
//       "cmpxchg16b",
//       "sse41",
//       "sse42",
//       "x2apic",
//       "movbe",
//       "popcnt",
//       "aesni",
//       "xsave",
//       "osxsave",
//       "avx",
//       "f16c",
//       "rdrand",
//       "fpu",
//       "vme",
//       "de",
//       "pse",
//       "tsc",
//       "msr",
//       "pae",
//       "mce",
//       "cx8",
//       "apic",
//       "sep",
//       "mtrr",
//       "pge",
//       "mca",
//       "cmov",
//       "pat",
//       "pse36",
//       "clfsh",
//       "mmx",
//       "fxsr",
//       "sse",
//       "sse2",
//       "htt",
//       "fsgsbase",
//       "bmi1",
//       "avx2",
//       "smep",
//       "bmi2",
//       "rep_movsb_stosb",
//       "invpcid",
//       "rdtm",
//       "rdta",
//       "rdseed",
//       "adx",
//       "smap",
//       "clflushopt",
//       "sha",
//       "clwb",
//       "umip",
//       "pku",
//       "ospke",
//       "rdpid",
//     ],
//     "golem.inf.cpu.cores": 8,
//     "golem.inf.cpu.model": "Stepping 0 Family 35 Model 160",
//     "golem.inf.cpu.threads": 15,
//     "golem.inf.cpu.vendor": "AuthenticAMD",
//     "golem.inf.mem.gib": 21.004196628928185,
//     "golem.inf.storage.gib": 678.5690704345703,
//     "golem.node.debug.subnet": "public",
//     "golem.node.id.name": "m1",
//     "golem.node.net.is-public": false,
//     "golem.runtime.capabilities": [
//       "inet",
//       "vpn",
//       "manifest-support",
//       "start-entrypoint",
//       "cuda, GA102 [GeForce RTX 3090]",
//       "cuda",
//       "gpu",
//     ],
//     "golem.runtime.name": "vm",
//     "golem.runtime.version": "0.3.0",
//     "golem.srv.caps.multi-activity": true,
//     "golem.srv.caps.payload-manifest": true,
//   },
//   constraints: "(&\n  (golem.srv.comp.expiration>1677234298081)\n  (golem.node.debug.subnet=public)\n)",
//   timestamp: "2023-02-24T15:12:33.472735Z",
//   state: "Initial",
//   _score: null,
// });
// proposals.value.push({
//   subscriptionId: "75fb0c0c043e44eeacb4a019a387832a-ee70e77ec616a104251016504c9997be654f81a966ac6bf7106a3d6e0a373617",
//   api: {
//     basePath: "http://127.0.0.1:7465/market-api/v1",
//     configuration: {
//       apiKey: "30c59fef7d8c4639b62d576bfb624e1a",
//       accessToken: "30c59fef7d8c4639b62d576bfb624e1a",
//       basePath: "http://127.0.0.1:7465/market-api/v1",
//     },
//   },
//   demandRequest: {
//     constraints:
//       "(&(golem.inf.mem.gib>=1)\n\t(golem.inf.storage.gib>=1)\n\t(golem.runtime.name=vm)\n\t(golem.inf.cpu.threads>=1)\n\t(golem.com.payment.platform.erc20-rinkeby-tglm.address=*)\n\t(golem.com.pricing.model=linear)\n\t(golem.node.debug.subnet=public))",
//     properties: {
//       "golem.srv.comp.task_package":
//         "hash:sha3:9a3b5d67b0b27746283cb5f287c13eab1beaa12d92a9f536b747c7ae:http://girepo.dev.golem.network:8000/local-image-c76719083b.gvmi\n",
//       "golem.srv.comp.vm.package_format": "gvmkit-squash",
//       "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xdc9b51c37a6f45a5fdc9af6ea04e00f7c64a2b6f",
//       "golem.srv.caps.multi-activity": true,
//       "golem.srv.comp.expiration": 1677251265172,
//       "golem.node.debug.subnet": "public",
//     },
//   },
//   eventTarget: {},
//   id: "R-b06fe110137d583bc5273f91d2663cee94e4be412a34d3428f7275fea646691f",
//   issuerId: "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//   properties: {
//     "golem.activity.caps.transfer.protocol": ["http", "gftp", "https"],
//     "golem.com.payment.debit-notes.accept-timeout?": 240,
//     "golem.com.payment.platform.erc20-goerli-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-mumbai-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.pricing.model": "linear",
//     "golem.com.pricing.model.linear.coeffs": [0.0001, 0.00005, 0],
//     "golem.com.scheme": "payu",
//     "golem.com.scheme.payu.debit-note.interval-sec?": 120,
//     "golem.com.scheme.payu.payment-timeout-sec?": 120,
//     "golem.com.usage.vector": ["golem.usage.cpu_sec", "golem.usage.duration_sec"],
//     "golem.inf.cpu.architecture": "x86_64",
//     "golem.inf.cpu.brand": "Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz",
//     "golem.inf.cpu.capabilities": [
//       "sse3",
//       "pclmulqdq",
//       "dtes64",
//       "monitor",
//       "dscpl",
//       "vmx",
//       "smx",
//       "eist",
//       "tm2",
//       "ssse3",
//       "fma",
//       "cmpxchg16b",
//       "pdcm",
//       "pcid",
//       "sse41",
//       "sse42",
//       "x2apic",
//       "movbe",
//       "popcnt",
//       "tsc_deadline",
//       "aesni",
//       "xsave",
//       "osxsave",
//       "avx",
//       "f16c",
//       "rdrand",
//       "fpu",
//       "vme",
//       "de",
//       "pse",
//       "tsc",
//       "msr",
//       "pae",
//       "mce",
//       "cx8",
//       "apic",
//       "sep",
//       "mtrr",
//       "pge",
//       "mca",
//       "cmov",
//       "pat",
//       "pse36",
//       "clfsh",
//       "ds",
//       "acpi",
//       "mmx",
//       "fxsr",
//       "sse",
//       "sse2",
//       "ss",
//       "htt",
//       "tm",
//       "pbe",
//       "fsgsbase",
//       "adjust_msr",
//       "bmi1",
//       "hle",
//       "avx2",
//       "smep",
//       "bmi2",
//       "rep_movsb_stosb",
//       "invpcid",
//       "rtm",
//       "deprecate_fpu_cs_ds",
//       "mpx",
//       "rdseed",
//       "adx",
//       "smap",
//       "clflushopt",
//       "processor_trace",
//       "sgx",
//     ],
//     "golem.inf.cpu.cores": 4,
//     "golem.inf.cpu.model": "Stepping 9 Family 6 Model 302",
//     "golem.inf.cpu.threads": 2,
//     "golem.inf.cpu.vendor": "GenuineIntel",
//     "golem.inf.mem.gib": 8,
//     "golem.inf.storage.gib": 100,
//     "golem.node.debug.subnet": "public",
//     "golem.node.id.name": "sycamore.h",
//     "golem.node.net.is-public": false,
//     "golem.runtime.capabilities": ["inet", "vpn", "manifest-support", "start-entrypoint"],
//     "golem.runtime.name": "vm",
//     "golem.runtime.version": "0.3.0",
//     "golem.srv.caps.multi-activity": true,
//     "golem.srv.caps.payload-manifest": true,
//   },
//   constraints: "(&\n  (golem.srv.comp.expiration>1676011020268)\n  (golem.node.debug.subnet=public)\n)",
//   timestamp: "2023-02-24T14:52:45.266946Z",
//   state: "Initial",
//   _score: null,
// });
// proposals.value.push({
//   subscriptionId: "75fb0c0c043e44eeacb4a019a387832a-ee70e77ec616a104251016504c9997be654f81a966ac6bf7106a3d6e0a373617",
//   api: {
//     basePath: "http://127.0.0.1:7465/market-api/v1",
//     configuration: {
//       apiKey: "30c59fef7d8c4639b62d576bfb624e1a",
//       accessToken: "30c59fef7d8c4639b62d576bfb624e1a",
//       basePath: "http://127.0.0.1:7465/market-api/v1",
//     },
//   },
//   demandRequest: {
//     constraints:
//       "(&(golem.inf.mem.gib>=1)\n\t(golem.inf.storage.gib>=1)\n\t(golem.runtime.name=vm)\n\t(golem.inf.cpu.threads>=1)\n\t(golem.com.payment.platform.erc20-rinkeby-tglm.address=*)\n\t(golem.com.pricing.model=linear)\n\t(golem.node.debug.subnet=public))",
//     properties: {
//       "golem.srv.comp.task_package":
//         "hash:sha3:9a3b5d67b0b27746283cb5f287c13eab1beaa12d92a9f536b747c7ae:http://girepo.dev.golem.network:8000/local-image-c76719083b.gvmi\n",
//       "golem.srv.comp.vm.package_format": "gvmkit-squash",
//       "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xdc9b51c37a6f45a5fdc9af6ea04e00f7c64a2b6f",
//       "golem.srv.caps.multi-activity": true,
//       "golem.srv.comp.expiration": 1677251265172,
//       "golem.node.debug.subnet": "public",
//     },
//   },
//   eventTarget: {},
//   id: "R-b06fe110137d583bc5273f91d2663cee94e4be412a34d3428f7275fea646691f",
//   issuerId: "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//   properties: {
//     "golem.activity.caps.transfer.protocol": ["http", "gftp", "https"],
//     "golem.com.payment.debit-notes.accept-timeout?": 240,
//     "golem.com.payment.platform.erc20-goerli-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-mumbai-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.pricing.model": "linear",
//     "golem.com.pricing.model.linear.coeffs": [0.0001, 0.00005, 0],
//     "golem.com.scheme": "payu",
//     "golem.com.scheme.payu.debit-note.interval-sec?": 120,
//     "golem.com.scheme.payu.payment-timeout-sec?": 120,
//     "golem.com.usage.vector": ["golem.usage.cpu_sec", "golem.usage.duration_sec"],
//     "golem.inf.cpu.architecture": "x86_64",
//     "golem.inf.cpu.brand": "Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz",
//     "golem.inf.cpu.capabilities": [
//       "sse3",
//       "pclmulqdq",
//       "dtes64",
//       "monitor",
//       "dscpl",
//       "vmx",
//       "smx",
//       "eist",
//       "tm2",
//       "ssse3",
//       "fma",
//       "cmpxchg16b",
//       "pdcm",
//       "pcid",
//       "sse41",
//       "sse42",
//       "x2apic",
//       "movbe",
//       "popcnt",
//       "tsc_deadline",
//       "aesni",
//       "xsave",
//       "osxsave",
//       "avx",
//       "f16c",
//       "rdrand",
//       "fpu",
//       "vme",
//       "de",
//       "pse",
//       "tsc",
//       "msr",
//       "pae",
//       "mce",
//       "cx8",
//       "apic",
//       "sep",
//       "mtrr",
//       "pge",
//       "mca",
//       "cmov",
//       "pat",
//       "pse36",
//       "clfsh",
//       "ds",
//       "acpi",
//       "mmx",
//       "fxsr",
//       "sse",
//       "sse2",
//       "ss",
//       "htt",
//       "tm",
//       "pbe",
//       "fsgsbase",
//       "adjust_msr",
//       "bmi1",
//       "hle",
//       "avx2",
//       "smep",
//       "bmi2",
//       "rep_movsb_stosb",
//       "invpcid",
//       "rtm",
//       "deprecate_fpu_cs_ds",
//       "mpx",
//       "rdseed",
//       "adx",
//       "smap",
//       "clflushopt",
//       "processor_trace",
//       "sgx",
//     ],
//     "golem.inf.cpu.cores": 4,
//     "golem.inf.cpu.model": "Stepping 9 Family 6 Model 302",
//     "golem.inf.cpu.threads": 2,
//     "golem.inf.cpu.vendor": "GenuineIntel",
//     "golem.inf.mem.gib": 8,
//     "golem.inf.storage.gib": 100,
//     "golem.node.debug.subnet": "public",
//     "golem.node.id.name": "sycamore.h",
//     "golem.node.net.is-public": false,
//     "golem.runtime.capabilities": ["inet", "vpn", "manifest-support", "start-entrypoint"],
//     "golem.runtime.name": "vm",
//     "golem.runtime.version": "0.3.0",
//     "golem.srv.caps.multi-activity": true,
//     "golem.srv.caps.payload-manifest": true,
//   },
//   constraints: "(&\n  (golem.srv.comp.expiration>1676011020268)\n  (golem.node.debug.subnet=public)\n)",
//   timestamp: "2023-02-24T14:52:45.266946Z",
//   state: "Initial",
//   _score: null,
// });
// proposals.value.push({
//   subscriptionId: "75fb0c0c043e44eeacb4a019a387832a-ee70e77ec616a104251016504c9997be654f81a966ac6bf7106a3d6e0a373617",
//   api: {
//     basePath: "http://127.0.0.1:7465/market-api/v1",
//     configuration: {
//       apiKey: "30c59fef7d8c4639b62d576bfb624e1a",
//       accessToken: "30c59fef7d8c4639b62d576bfb624e1a",
//       basePath: "http://127.0.0.1:7465/market-api/v1",
//     },
//   },
//   demandRequest: {
//     constraints:
//       "(&(golem.inf.mem.gib>=1)\n\t(golem.inf.storage.gib>=1)\n\t(golem.runtime.name=vm)\n\t(golem.inf.cpu.threads>=1)\n\t(golem.com.payment.platform.erc20-rinkeby-tglm.address=*)\n\t(golem.com.pricing.model=linear)\n\t(golem.node.debug.subnet=public))",
//     properties: {
//       "golem.srv.comp.task_package":
//         "hash:sha3:9a3b5d67b0b27746283cb5f287c13eab1beaa12d92a9f536b747c7ae:http://girepo.dev.golem.network:8000/local-image-c76719083b.gvmi\n",
//       "golem.srv.comp.vm.package_format": "gvmkit-squash",
//       "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xdc9b51c37a6f45a5fdc9af6ea04e00f7c64a2b6f",
//       "golem.srv.caps.multi-activity": true,
//       "golem.srv.comp.expiration": 1677251265172,
//       "golem.node.debug.subnet": "public",
//     },
//   },
//   eventTarget: {},
//   id: "R-b06fe110137d583bc5273f91d2663cee94e4be412a34d3428f7275fea646691f",
//   issuerId: "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//   properties: {
//     "golem.activity.caps.transfer.protocol": ["http", "gftp", "https"],
//     "golem.com.payment.debit-notes.accept-timeout?": 240,
//     "golem.com.payment.platform.erc20-goerli-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-mumbai-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.pricing.model": "linear",
//     "golem.com.pricing.model.linear.coeffs": [0.0001, 0.00005, 0],
//     "golem.com.scheme": "payu",
//     "golem.com.scheme.payu.debit-note.interval-sec?": 120,
//     "golem.com.scheme.payu.payment-timeout-sec?": 120,
//     "golem.com.usage.vector": ["golem.usage.cpu_sec", "golem.usage.duration_sec"],
//     "golem.inf.cpu.architecture": "x86_64",
//     "golem.inf.cpu.brand": "Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz",
//     "golem.inf.cpu.capabilities": [
//       "sse3",
//       "pclmulqdq",
//       "dtes64",
//       "monitor",
//       "dscpl",
//       "vmx",
//       "smx",
//       "eist",
//       "tm2",
//       "ssse3",
//       "fma",
//       "cmpxchg16b",
//       "pdcm",
//       "pcid",
//       "sse41",
//       "sse42",
//       "x2apic",
//       "movbe",
//       "popcnt",
//       "tsc_deadline",
//       "aesni",
//       "xsave",
//       "osxsave",
//       "avx",
//       "f16c",
//       "rdrand",
//       "fpu",
//       "vme",
//       "de",
//       "pse",
//       "tsc",
//       "msr",
//       "pae",
//       "mce",
//       "cx8",
//       "apic",
//       "sep",
//       "mtrr",
//       "pge",
//       "mca",
//       "cmov",
//       "pat",
//       "pse36",
//       "clfsh",
//       "ds",
//       "acpi",
//       "mmx",
//       "fxsr",
//       "sse",
//       "sse2",
//       "ss",
//       "htt",
//       "tm",
//       "pbe",
//       "fsgsbase",
//       "adjust_msr",
//       "bmi1",
//       "hle",
//       "avx2",
//       "smep",
//       "bmi2",
//       "rep_movsb_stosb",
//       "invpcid",
//       "rtm",
//       "deprecate_fpu_cs_ds",
//       "mpx",
//       "rdseed",
//       "adx",
//       "smap",
//       "clflushopt",
//       "processor_trace",
//       "sgx",
//     ],
//     "golem.inf.cpu.cores": 4,
//     "golem.inf.cpu.model": "Stepping 9 Family 6 Model 302",
//     "golem.inf.cpu.threads": 2,
//     "golem.inf.cpu.vendor": "GenuineIntel",
//     "golem.inf.mem.gib": 8,
//     "golem.inf.storage.gib": 100,
//     "golem.node.debug.subnet": "public",
//     "golem.node.id.name": "sycamore.h",
//     "golem.node.net.is-public": false,
//     "golem.runtime.capabilities": ["inet", "vpn", "manifest-support", "start-entrypoint"],
//     "golem.runtime.name": "vm",
//     "golem.runtime.version": "0.3.0",
//     "golem.srv.caps.multi-activity": true,
//     "golem.srv.caps.payload-manifest": true,
//   },
//   constraints: "(&\n  (golem.srv.comp.expiration>1676011020268)\n  (golem.node.debug.subnet=public)\n)",
//   timestamp: "2023-02-24T14:52:45.266946Z",
//   state: "Initial",
//   _score: null,
// });
// proposals.value.push({
//   subscriptionId: "75fb0c0c043e44eeacb4a019a387832a-ee70e77ec616a104251016504c9997be654f81a966ac6bf7106a3d6e0a373617",
//   api: {
//     basePath: "http://127.0.0.1:7465/market-api/v1",
//     configuration: {
//       apiKey: "30c59fef7d8c4639b62d576bfb624e1a",
//       accessToken: "30c59fef7d8c4639b62d576bfb624e1a",
//       basePath: "http://127.0.0.1:7465/market-api/v1",
//     },
//   },
//   demandRequest: {
//     constraints:
//       "(&(golem.inf.mem.gib>=1)\n\t(golem.inf.storage.gib>=1)\n\t(golem.runtime.name=vm)\n\t(golem.inf.cpu.threads>=1)\n\t(golem.com.payment.platform.erc20-rinkeby-tglm.address=*)\n\t(golem.com.pricing.model=linear)\n\t(golem.node.debug.subnet=public))",
//     properties: {
//       "golem.srv.comp.task_package":
//         "hash:sha3:9a3b5d67b0b27746283cb5f287c13eab1beaa12d92a9f536b747c7ae:http://girepo.dev.golem.network:8000/local-image-c76719083b.gvmi\n",
//       "golem.srv.comp.vm.package_format": "gvmkit-squash",
//       "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xdc9b51c37a6f45a5fdc9af6ea04e00f7c64a2b6f",
//       "golem.srv.caps.multi-activity": true,
//       "golem.srv.comp.expiration": 1677251265172,
//       "golem.node.debug.subnet": "public",
//     },
//   },
//   eventTarget: {},
//   id: "R-b06fe110137d583bc5273f91d2663cee94e4be412a34d3428f7275fea646691f",
//   issuerId: "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//   properties: {
//     "golem.activity.caps.transfer.protocol": ["http", "gftp", "https"],
//     "golem.com.payment.debit-notes.accept-timeout?": 240,
//     "golem.com.payment.platform.erc20-goerli-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-mumbai-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.erc20-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.payment.platform.zksync-rinkeby-tglm.address": "0xd385526f0a2d9165ba9aa704f4b9f33e85f7e8c2",
//     "golem.com.pricing.model": "linear",
//     "golem.com.pricing.model.linear.coeffs": [0.0001, 0.00005, 0],
//     "golem.com.scheme": "payu",
//     "golem.com.scheme.payu.debit-note.interval-sec?": 120,
//     "golem.com.scheme.payu.payment-timeout-sec?": 120,
//     "golem.com.usage.vector": ["golem.usage.cpu_sec", "golem.usage.duration_sec"],
//     "golem.inf.cpu.architecture": "x86_64",
//     "golem.inf.cpu.brand": "Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz",
//     "golem.inf.cpu.capabilities": [
//       "sse3",
//       "pclmulqdq",
//       "dtes64",
//       "monitor",
//       "dscpl",
//       "vmx",
//       "smx",
//       "eist",
//       "tm2",
//       "ssse3",
//       "fma",
//       "cmpxchg16b",
//       "pdcm",
//       "pcid",
//       "sse41",
//       "sse42",
//       "x2apic",
//       "movbe",
//       "popcnt",
//       "tsc_deadline",
//       "aesni",
//       "xsave",
//       "osxsave",
//       "avx",
//       "f16c",
//       "rdrand",
//       "fpu",
//       "vme",
//       "de",
//       "pse",
//       "tsc",
//       "msr",
//       "pae",
//       "mce",
//       "cx8",
//       "apic",
//       "sep",
//       "mtrr",
//       "pge",
//       "mca",
//       "cmov",
//       "pat",
//       "pse36",
//       "clfsh",
//       "ds",
//       "acpi",
//       "mmx",
//       "fxsr",
//       "sse",
//       "sse2",
//       "ss",
//       "htt",
//       "tm",
//       "pbe",
//       "fsgsbase",
//       "adjust_msr",
//       "bmi1",
//       "hle",
//       "avx2",
//       "smep",
//       "bmi2",
//       "rep_movsb_stosb",
//       "invpcid",
//       "rtm",
//       "deprecate_fpu_cs_ds",
//       "mpx",
//       "rdseed",
//       "adx",
//       "smap",
//       "clflushopt",
//       "processor_trace",
//       "sgx",
//     ],
//     "golem.inf.cpu.cores": 4,
//     "golem.inf.cpu.model": "Stepping 9 Family 6 Model 302",
//     "golem.inf.cpu.threads": 2,
//     "golem.inf.cpu.vendor": "GenuineIntel",
//     "golem.inf.mem.gib": 8,
//     "golem.inf.storage.gib": 100,
//     "golem.node.debug.subnet": "public",
//     "golem.node.id.name": "sycamore.h",
//     "golem.node.net.is-public": false,
//     "golem.runtime.capabilities": ["inet", "vpn", "manifest-support", "start-entrypoint"],
//     "golem.runtime.name": "vm",
//     "golem.runtime.version": "0.3.0",
//     "golem.srv.caps.multi-activity": true,
//     "golem.srv.caps.payload-manifest": true,
//   },
//   constraints: "(&\n  (golem.srv.comp.expiration>1676011020268)\n  (golem.node.debug.subnet=public)\n)",
//   timestamp: "2023-02-24T14:52:45.266946Z",
//   state: "Initial",
//   _score: null,
// });
</script>
<style lang="scss" scoped>
.expandable {
  padding: 1rem;

  dl {
    dt {
      font-weight: bold;
    }
  }
}
</style>
