name: "Cleanup test environment"
description: "Cleanup test environment"
inputs:
  type:
    description: "Type of test"
    required: true
    default: "test"
runs:
  using: "composite"
  steps:
    - name: Collect logs from providers and requestor
      shell: bash
      if: always()
      run: |
        mkdir log-output
        docker compose -f tests/docker/docker-compose.yml logs provider-1 > log-output/${{inputs.type}}-provider-1.log
        docker compose -f tests/docker/docker-compose.yml logs provider-2 > log-output/${{inputs.type}}-provider-2.log
        docker compose -f tests/docker/docker-compose.yml logs requestor > log-output/${{inputs.type}}-requestor.log

    - name: Upload provider output and logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{inputs.type}}-golem-provider-and-requestor-logs
        path: log-output

    - name: Cleanup Docker
      shell: bash
      if: always()
      run: |
        c=$(docker ps -q)
        [[ $c ]] && docker kill $c
        docker system prune -af
