name: "Prepare providers and requestor"
description: "Prepare providers and requestor"
inputs:
  type:
    description: "Type of test"
    required: true
    default: "test"
runs:
  using: "composite"
  steps:
    - name: Use random string for subnet
      shell: bash
      # Use a random string to avoid other providers on the same subnet which might cause tests to fail because it expects only providers named provider-1 and provider-2
      run: echo "YAGNA_SUBNET=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8 ; echo '')" >> $GITHUB_ENV

    - name: Set up Versions
      shell: bash
      run: |
        echo "PAYMENT_NETWORK=${PAYMENT_NETWORK}" >> $GITHUB_ENV
        echo "PROVIDER_VERSION=${PROVIDER_VERSION}" >> $GITHUB_ENV
        echo "REQUESTOR_VERSION=${REQUESTOR_VERSION}" >> $GITHUB_ENV
        echo "PROVIDER_WASI_VERSION=${PROVIDER_WASI_VERSION}" >> $GITHUB_ENV
        echo "PROVIDER_VM_VERSION=${PROVIDER_VM_VERSION}" >> $GITHUB_ENV

    - name: Build the docker containers
      shell: bash
      run: |
        docker compose -f tests/docker/docker-compose.yml build \
          --build-arg UBUNTU_VERSION=22.04 \
          --build-arg YA_CORE_PROVIDER_VERSION=${PROVIDER_VERSION} \
          --build-arg YA_CORE_REQUESTOR_VERSION=${REQUESTOR_VERSION} \
          --build-arg YA_WASI_VERSION=${PROVIDER_WASI_VERSION} \
          --build-arg YA_VM_VERSION=${PROVIDER_VM_VERSION}

    - name: Start the docker containers
      shell: bash
      run: |
        sudo service docker restart
        docker compose -f tests/docker/docker-compose.yml down
        docker compose -f tests/docker/docker-compose.yml up -d

    - name: Fund the requestor
      shell: bash
      run: |
        sleep 10
        echo "Going to fund the requestor"
        docker exec -t docker-requestor-1 /bin/sh -c "/golem-js/tests/docker/fundRequestor.sh"
        echo "Successfully funded the requestor"

    - name: Install and build the SDK in the docker container
      shell: bash
      run: |
        echo "Going to build the SDK on the requestor"
        docker exec -t docker-requestor-1 /bin/sh -c "cd /golem-js && npm i --no-progress && npm run build"
        echo "Successfully built the SDK on the requestor"

    - name: Install Cypress
      if: ${{ inputs.type == 'cypress' }}
      shell: bash
      run: |
        docker exec -t docker-requestor-1 /bin/sh -c "cd /golem-js && ./node_modules/.bin/cypress install"

    - name: Run a preliminary scan of offers
      shell: bash
      run: |
        docker exec -t docker-requestor-1 /bin/sh -c "npm install --no-progress -g @prekucki/wait-for-n && wait-for-n --limit=6 --appkey=try_golem --subnet=$YAGNA_SUBNET"

    - name: List down sessions seen on that requestor
      shell: bash
      run: |
        docker exec docker-requestor-1 /bin/sh -c "yagna net sessions"

    - name: Run a secondary scan of offers
      shell: bash
      run: |
        docker exec -t docker-requestor-1 /bin/sh -c "npx --no-progress --yes @golem-sdk/cli market scan -k try_golem --subnet-tag $YAGNA_SUBNET --payment-network $PAYMENT_NETWORK"
