name: Send workflow dispatch event

on:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Trigger other workflow
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g")
          curl -X POST \
          -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          "https://api.github.com/repos/golemfactory/golem-docs/actions/workflows/build-reference-and-issue-pr.yml/dispatches" \
          --data '{"branch": "'"$BRANCH_NAME"'"}'
