name: Integrations Tests

on:
  push:
    branches:
      - master
      # - <your-branch>    # put your branch name here to test it @ GH Actions
  pull_request:
    branches:
      - master

jobs:

  goth-tests:
    name: Run integration tests
    runs-on: goth
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'

      - name: Build yajsapi
        run: |
          cd examples
          npm install
          npm build

      - name: Configure python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'

      - name: Configure poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.4

      - name: Install dependencies
        run: |
          cd tests/goth/
          poetry env use python3.8
          poetry install

      - name: Log in to GitHub Docker repository
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{github.actor}} --password-stdin

      - name: Run test suite
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd tests/goth/
          poetry run python -m goth create-assets assets
          echo yagnaurl2=$YAGNA_API_URL
          echo yagnaurl1=${{env.YAGNA_API_URL}}
          export YAGNA_MARKET_URL=$YAGNA_API_URL/market-api/v1
          export YAGNA_PAYMENT_URL=$YAGNA_API_URL/payment-api/v1
          export YAGNA_ACTIVITY_URL=$YAGNA_API_URL/activity-api/v1
          poetry run pytest -svx .

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
           name: goth-logs
           path: /tmp/goth-tests

      # Only relevant for self-hosted runners
      - name: Remove test logs
        if: always()
        run: rm -rf /tmp/goth-tests

      # Only relevant for self-hosted runners
      - name: Remove poetry virtual env
        if: always()
        # Python version below should agree with the version set up by this job.
        # In future we'll be able to use the `--all` flag here to remove envs for
        # all Python versions (https://github.com/python-poetry/poetry/issues/3208).
        run: |
          cd tests/goth/
          poetry env remove python3.8 